---
title: "Merging and Joining Data"
teaching: 45
exercises: 10
questions:
- "How can I combine data from different sources?"
objectives:
- "Learn how to stack data frames (ex. different years' data)"
- "Learn how to join - inner, outer, etc."
- "Explore after a join to verify results as expected"
keypoints:
- "Use `merge()` to stack data"
- "Use `merge()` to join data"
- "Understand joins"
source: Rmd
---

```{r, include=FALSE}
source("../bin/chunk-options.R")
knitr_fig_path("01-")
```

## Introduction goes here

Text


```{r, eval=FALSE}
bmi_df <- read.xport('data/BMX_I.XPT') 
bp_df <- read.xport('data/BPX_I.XPT')
cbc_df <- read.xport('data/CBC_I.XPT')
glu_df <- read.xport('data/GLU_I.XPT')
tg_df <- read.xport('data/TRIGLY_I.XPT')
hdl_df <- read.xport('data/HDL_I.XPT')
tc_df <- read.xport('data/TCHOL_I.XPT')
```

Now that we have all the files read in, let's merge.
From bmi_df we are keeping: BMXBMI
from bp_df: PBXPLS (pules), BPXSY1 (SBP), PBXDI1 (DPB),
tg_df : LBXTR (triglycerides mg/dL), LBDLDL (LDL mg/dL)
tc_df: LBXTC (total chol mg/dL)
hdl_df: LBDHDD (HDL mg/dL)
cbc_df: LBXWBCSI (WBCs 1000cells/uL)
glu_df: LBXGLU (glucose fasting mg/dL)

HERE WE NEED TO CONSIDER DPLYR FOR JOINING. #TODO

```{r, eval=FALSE}
merge_df <- merge(demographics, bmi_df[ ,c("SEQN", "BMXBMI")])
merge_df <- merge (merge_df, bp_df[ ,c("SEQN", "BPXSY1", "BPXDI1")])
merge_df <- merge(merge_df, tg_df[ , c("SEQN", "LBXTR", "LBDLDL")])
merge_df <- merge(merge_df, tc_df[ , c("SEQN", "LBXTC")])
merge_df <- merge(merge_df, hdl_df[ , c("SEQN", "LBDHDD")])
merge_df <- merge(merge_df, cbc_df[ , c("SEQN", "LBXWBCSI")])
merge_df <- merge(merge_df, glu_df[ , c("SEQN", "LBXGLU")])
```

```{r, eval=FALSE}
write.csv(merge_df, file = 'data_out/merge.csv', row.names = FALSE)
```

