---
title: "Creating summary tables"
teaching: 45
exercises: 10
questions:
- "How can I create a 'Table 1' style table?"
- "How can export tables and data"
objectives:
- "make a new variable from other(s) - e.g. log transform"
- "Create a categorical (0/1) out of continuous"
- "Stratify"
keypoints:
- "Use `stargazer` package to make beautiful tables"
- "Use R functions to export data (in different formats?)"
source: Rmd
---

```{r, include=FALSE}
source("../bin/chunk-options.R")
knitr_fig_path("07-")
```

# TODO

Hide this:
```{r}
swan_df <- read.delim('data/SWAN.tsv')
```

# Table 1

Creating a "Table 1" is an almost-universal step in conducting an analysis in public health data.  Fortunately for us, there are now some R libraries we can use to make this task easier.  Let's use the `tableone` library:

```{r}
#install.packages('tableone')
library(tableone)
```

#TODO: Move this to episode 5
```{r}
swan_df$HEART <- as.factor(swan_df$HEART)
levels(swan_df$HEART) <- c('No', 'Yes')
```


Let's take a look at the help for `tableone`
```{r}
CreateTableOne(data = swan_df, vars = c('ARTHRIT', 'DEGREE'),
               strata = 'HEART')
```
